[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src *; media-src *; img-src * data: blob:; connect-src *; script-src * 'unsafe-inline' 'unsafe-eval'; style-src * 'unsafe-inline';"
    Permissions-Policy = "camera=(self), microphone=(), geolocation=(self)"

[build]
  publish = "dist"
  command = "npm run build"
  
[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200